
---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"





  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5




  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
















