function New-CIPPAPIConfig {

    [CmdletBinding(SupportsShouldProcess)]
    param (
        $APIName = 'CIPP API Config',
        $Headers,
        [switch]$ResetSecret,
        [string]$AppName,
        [Alias('ClientId')]
        [string]$AppId
    )

    $Permissions = Get-GraphToken -tenantid $env:TenantID -scope 'https://graph.microsoft.com/.default' -AsApp $true -SkipCache $true -ReturnRefresh $true
    $Token = Read-JwtAccessDetails -Token $Permissions.access_token
    $Permissions = $Token.Roles | Where-Object { $_ -match 'Application.ReadWrite.All' -or $_ -match 'Directory.ReadWrite.All' }
    if (!$Permissions -or $Permissions.Count -lt 2) {
        Write-LogMessage -headers $Headers -API $APINAME -tenant 'None '-message 'Insufficient permissions to create API App' -Sev 'Error'
        throw 'Insufficient permissions to create API App. This integration requires the following Application permissions in the partner tenant. Application.ReadWrite.All, Directory.ReadWrite.All'
    }

    try {
        if ($AppId) {
            $APIApp = New-GraphGetRequest -uri "https://graph.microsoft.com/v1.0/applications(appid='$($AppId)')" -NoAuthCheck $true -AsApp $true
            Write-Information "Found existing app with AppId $AppId"
        } else {
            $CreateBody = @{
                api                    = @{
                    oauth2PermissionScopes = @(
                        @{
                            adminConsentDescription = 'Allow the application to access CIPP-API on behalf of the signed-in user.'
                            adminConsentDisplayName = 'Access CIPP-API'
                            id                      = 'ba7ffeff-96ea-4ac4-9822-1bcfee9adaa4'
                            isEnabled               = $true
                            type                    = 'User'
                            userConsentDescription  = 'Allow the application to access CIPP-API on your behalf.'
                            userConsentDisplayName  = 'Access CIPP-API'
                            value                   = 'user_impersonation'
                        }
                    )
                }
                displayName            = $AppName
                requiredResourceAccess = @(
                    @{
                        resourceAccess = @(
                            @{
                                id   = 'e1fe6dd8-ba31-4d61-89e7-88639da4683d'
                                type = 'Scope'
                            }
                        )
                        resourceAppId  = '00000003-0000-0000-c000-000000000000'
                    }
                )
                signInAudience         = 'AzureADMyOrg'
                web                    = @{
                    homePageUrl           = 'https://cipp.app'
                    implicitGrantSettings = @{
                        enableAccessTokenIssuance = $false
                        enableIdTokenIssuance     = $true
                    }
                    redirectUris          = @("https://$($env:WEBSITE_HOSTNAME)/.auth/login/aad/callback")
                }
            } | ConvertTo-Json -Depth 10 -Compress

            if ($PSCmdlet.ShouldProcess($AppName, 'Create API App')) {
                Write-Information 'Creating app'
                Write-Information $CreateBody
                $Step = 'Creating Application'
                $APIApp = New-GraphPOSTRequest -uri 'https://graph.microsoft.com/v1.0/applications' -AsApp $true -NoAuthCheck $true -type POST -body $CreateBody

                try {
                    $PolicyUpdate = Update-AppManagementPolicy -ApplicationId $APIApp.appId
                    Write-Information $PolicyUpdate.PolicyAction
                } catch {
                    Write-Information "Failed to update app management policy: $($_.Exception.Message)"
                }

                Write-Information 'Creating password'
                $Step = 'Creating Application Password'
                $AppManagementPolicy = New-GraphGetRequest -uri "https://graph.microsoft.com/v1.0/policies/defaultAppManagementPolicy" -AsApp $true -NoAuthCheck $true
                $PasswordExpirationPolicy =  $AppManagementPolicy.applicationRestrictions.passwordcredentials |
                    Where-Object { $_.restrictionType -eq 'passwordLifetime' }
                $PasswordBody = $null
                if (-not ($PasswordExpirationPolicy.state -eq 'disabled' -or $null -eq $PasswordExpirationPolicy.state)) {
                    $TimeToExpiration = [System.Xml.XmlConvert]::ToTimeSpan($PasswordExpirationPolicy.maxLifetime)
                    $ExpirationDate = (Get-Date).AddDays($TimeToExpiration.Days).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
                    $PasswordBody = "{`"passwordCredential`":{`"displayName`":`"Generated by API Setup`",`"endDateTime`":`"$ExpirationDate`"}}"
                } else {
                    $PasswordBody = "{`"passwordCredential`":{`"displayName`":`"Generated by API Setup`"}}"
                }

                for ($Attempt = 1; $Attempt -le 6; $Attempt++) {
                    try {
                        $APIPassword = New-GraphPOSTRequest -uri "https://graph.microsoft.com/v1.0/applications/$($APIApp.id)/addPassword" -AsApp $true -NoAuthCheck $true -type POST -body $PasswordBody -maxRetries 3
                        break
                    } catch {
                        $IsNotReplicatedYet = $_.Exception.Message -match "Resource '.*' does not exist or one of its queried reference-property objects are not present"
                        if ($IsNotReplicatedYet -and $Attempt -lt 6) {
                            $DelaySeconds = 3
                            Write-Information "Application object not yet replicated for addPassword (attempt $Attempt of 6). Retrying in $DelaySeconds second(s)."
                            Start-Sleep -Seconds $DelaySeconds
                            try {
                                $APIApp = New-GraphGetRequest -uri "https://graph.microsoft.com/v1.0/applications(appid='$($APIApp.appId)')" -NoAuthCheck $true -AsApp $true
                            } catch {
                                Write-Information "Application lookup retry failed before addPassword retry: $($_.Exception.Message)"
                            }
                            continue
                        }
                        throw
                    }
                }

                if (-not $APIPassword) {
                    throw 'Failed to create application password after retries. The app may not have replicated yet; wait a moment and retry.'
                }
                Write-Information 'Adding App URL'
                $Step = 'Adding Application Identifier URI'
                $IdentifierUriBody = "{`"identifierUris`":[`"api://$($APIApp.appId)`"]}"
                $IdentifierUriUpdated = $false
                for ($Attempt = 1; $Attempt -le 6; $Attempt++) {
                    try {
                        New-GraphPOSTRequest -uri "https://graph.microsoft.com/v1.0/applications/$($APIApp.id)" -AsApp $true -NoAuthCheck $true -type PATCH -body $IdentifierUriBody -maxRetries 3 | Out-Null
                        $IdentifierUriUpdated = $true
                        break
                    } catch {
                        $IsNotReplicatedYet = $_.Exception.Message -match "Resource '.*' does not exist or one of its queried reference-property objects are not present"
                        if ($IsNotReplicatedYet -and $Attempt -lt 6) {
                            $DelaySeconds = 3
                            Write-Information "Application object not yet replicated for identifier URI update (attempt $Attempt of 6). Retrying in $DelaySeconds second(s)."
                            Start-Sleep -Seconds $DelaySeconds
                            try {
                                $APIApp = New-GraphGetRequest -uri "https://graph.microsoft.com/v1.0/applications(appid='$($APIApp.appId)')" -NoAuthCheck $true -AsApp $true
                            } catch {
                                Write-Information "Application lookup retry failed before identifier URI retry: $($_.Exception.Message)"
                            }
                            continue
                        }
                        throw
                    }
                }

                if (-not $IdentifierUriUpdated) {
                    throw 'Failed to set application identifier URI after retries. The app may not have replicated yet; wait a moment and retry.'
                }
                Write-LogMessage -headers $Headers -API $APINAME -tenant 'None '-message "Created CIPP-API App with name '$($APIApp.displayName)'." -Sev 'info'
            }
        }

        if ($APIApp) {
            $Step = 'Validating Service Principal'
            $ServicePrincipal = $null
            try {
                $ServicePrincipal = New-GraphGetRequest -uri "https://graph.microsoft.com/v1.0/servicePrincipals(appId='$($APIApp.appId)')" -NoAuthCheck $true -AsApp $true
            } catch {
                Write-Information "Service principal lookup failed or not found for AppId $($APIApp.appId): $($_.Exception.Message)"
            }

            if (-not $ServicePrincipal) {
                if ($PSCmdlet.ShouldProcess($APIApp.displayName, 'Create Service Principal')) {
                    Write-Information 'Creating missing service principal'
                    $Step = 'Creating Service Principal'
                    $ServicePrincipalDisplayName = $APIApp.displayName ?? $AppName
                    $ServicePrincipalBody = "{`"accountEnabled`":true,`"appId`":`"$($APIApp.appId)`",`"displayName`":`"$ServicePrincipalDisplayName`",`"tags`":[`"WindowsAzureActiveDirectoryIntegratedApp`",`"AppServiceIntegratedApp`"]}"
                    for ($Attempt = 1; $Attempt -le 6; $Attempt++) {
                        try {
                            $ServicePrincipal = New-GraphPOSTRequest -uri 'https://graph.microsoft.com/v1.0/serviceprincipals' -AsApp $true -NoAuthCheck $true -type POST -body $ServicePrincipalBody -maxRetries 3
                            break
                        } catch {
                            if ($Attempt -lt 6) {
                                Start-Sleep -Seconds 3
                                 Write-Information "Retrying service principal creation for AppId $($APIApp.appId) (attempt $Attempt of 6) after failure: $($_.Exception.Message)"
                                continue
                            }
                            throw
                        }
                    }
                }
            } else {
                Write-Information "Service principal already exists for AppId $($APIApp.appId)"
            }
        }

        if ($ResetSecret.IsPresent -and $APIApp) {
            if ($PSCmdlet.ShouldProcess($APIApp.displayName, 'Reset API Secret')) {
                $Step = 'Resetting Application Password'
                Write-Information 'Removing all old passwords'
                $Requests = @(
                    @{
                        id      = 'removeOldPasswords'
                        method  = 'PATCH'
                        url     = "applications/$($APIApp.id)/"
                        headers = @{
                            'Content-Type' = 'application/json'
                        }
                        body    = @{
                            passwordCredentials = @()
                        }
                    },
                    @{
                        id        = 'addNewPassword'
                        method    = 'POST'
                        url       = "applications/$($APIApp.id)/addPassword"
                        headers   = @{
                            'Content-Type' = 'application/json'
                        }
                        body      = @{
                            passwordCredential = @{
                                displayName = 'Generated by API Setup'
                            }
                        }
                        dependsOn = @('removeOldPasswords')
                    }
                )
                $BatchResponse = New-GraphBulkRequest -tenantid $env:TenantID -NoAuthCheck $true -asapp $true -Requests $Requests
                $APIPassword = $BatchResponse | Where-Object { $_.id -eq 'addNewPassword' } | Select-Object -ExpandProperty body
                Write-LogMessage -headers $Headers -API $APINAME -tenant 'None '-message "Reset CIPP-API Password for '$($APIApp.displayName)'." -Sev 'info'
            }
        }

        return @{
            AppName           = $APIApp.displayName
            ApplicationID     = $APIApp.appId
            ApplicationSecret = $APIPassword.secretText
            Results           = $Results
        }

    } catch {
        $ErrorMessage = Get-CippException -Exception $_
        Write-Information ($ErrorMessage | ConvertTo-Json -Depth 10)
        Write-LogMessage -headers $Headers -API $APINAME -tenant 'None' -message "CIPP-API Setup failed at step ($Step): $($ErrorMessage.NormalizedError) Linenumber: $($_.InvocationInfo.ScriptLineNumber)" -Sev 'Error' -LogData $ErrorMessage

        $Exception = [System.Exception]::new("Failed to setup CIPP-API Access: $($ErrorMessage.NormalizedError)")
        if ($APIApp) {
            if ($APIApp.appId) {
                $Exception.Data['ApplicationID'] = [string]$APIApp.appId
            }
            if ($APIApp.id) {
                $Exception.Data['ApplicationObjectID'] = [string]$APIApp.id
            }
            if ($APIApp.displayName) {
                $Exception.Data['ApplicationDisplayName'] = [string]$APIApp.displayName
            }
        }

        throw $Exception
    }
}
