function Invoke-CIPPBaselineDeployCheckChromeExtension {
    <#
    .SYNOPSIS
        DeployCheckChromeExtension executor: deploys the Check by CyberDrain Win32 app.
    .DESCRIPTION
        The classic's write, verbatim: build the install/uninstall/detection scripts from the
        configured settings, fingerprint the install script into the app description
        ([cfg:hash]), clean up the legacy OMA-URI policies, and redeploy ONLY when the
        fingerprint changed - Intune sees a new detection script and re-runs it fleet-wide.
        The definition runs checkBeforeRun:false so this self-gating write happens every
        remediation run, exactly as the classic's remediate block did.
    .FUNCTIONALITY
        Internal
    #>
    [CmdletBinding()]
    param(
        $Remediate,
        $TenantFilter,
        $Current
    )

    $ChromeExtensionId = 'benimdeioplgkhanklclahllklceahbe'
    $EdgeExtensionId = 'knepjpocdagponkonnbggpcnhnaikajg'
    $AppDisplayName = 'Check by CyberDrain - Browser Extension'

    $CippConfigTable = Get-CippTable -tablename Config
    $CippConfig = Get-CIPPAzDataTableEntity @CippConfigTable -Filter "PartitionKey eq 'InstanceProperties' and RowKey eq 'CIPPURL'"
    $CIPPURL = 'https://{0}' -f $CippConfig.Value

    $ShowNotifications = [int][bool]($Remediate.showNotifications ?? $true)
    $EnableValidPageBadge = [int][bool]($Remediate.enableValidPageBadge ?? $false)
    $EnablePageBlocking = [int][bool]($Remediate.enablePageBlocking ?? $true)
    $ForceToolbarPin = [int][bool]($Remediate.forceToolbarPin ?? $true)
    $EnableCippReporting = [int][bool]($Remediate.enableCippReporting ?? $false)
    $CippServerUrl = $CIPPURL
    $CippTenantId = $TenantFilter
    $CustomRulesUrl = "$($Remediate.customRulesUrl ?? '')"
    $UpdateInterval = [int]"$($Remediate.updateInterval ?? 24)"
    $EnableDebugLogging = [int][bool]($Remediate.enableDebugLogging ?? $false)
    $EnableGenericWebhook = [int][bool]($Remediate.enableGenericWebhook ?? $false)
    $WebhookUrl = "$($Remediate.webhookUrl ?? '')"
    $WebhookEvents = @($Remediate.webhookEvents | ForEach-Object { "$($_.value ?? $_)" } | Where-Object { $_ })
    $UrlAllowlist = @($Remediate.urlAllowlist | ForEach-Object { "$($_.value ?? $_)" } | Where-Object { $_ })
    $DomainSquattingEnabled = [int][bool]($Remediate.domainSquattingEnabled ?? $true)
    $CompanyName = "$($Remediate.companyName ?? '')"
    $ProductName = "$($Remediate.productName ?? '')"
    $SupportEmail = "$($Remediate.supportEmail ?? '')"
    $SupportUrl = "$($Remediate.supportUrl ?? '')"
    $PrivacyPolicyUrl = "$($Remediate.privacyPolicyUrl ?? '')"
    $AboutUrl = "$($Remediate.aboutUrl ?? '')"
    $PrimaryColor = if ($Remediate.primaryColor) { '#{0}' -f ("$($Remediate.primaryColor)" -replace '^#+', '') } else { '#F77F00' }
    $LogoUrl = "$($Remediate.logoUrl ?? '')"

    $InstallScript = @"
# Check Chrome Extension - Install Script (generated by CIPP)
`$chromeExtensionId = '$ChromeExtensionId'
`$edgeExtensionId = '$EdgeExtensionId'

# Extension settings per browser
`$browsers = @(
    @{
        ExtensionId        = `$chromeExtensionId
        UpdateUrl          = 'https://clients2.google.com/service/update2/crx'
        ManagedStorageKey  = "HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\`$chromeExtensionId\policy"
        ExtSettingsKey     = "HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\`$chromeExtensionId"
        ToolbarProp        = 'toolbar_pin'
        ToolbarPinned      = 'force_pinned'
        ToolbarUnpinned    = 'default_unpinned'
    },
    @{
        ExtensionId        = `$edgeExtensionId
        UpdateUrl          = 'https://edge.microsoft.com/extensionwebstorebase/v1/crx'
        ManagedStorageKey  = "HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\`$edgeExtensionId\policy"
        ExtSettingsKey     = "HKLM:\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\`$edgeExtensionId"
        ToolbarProp        = 'toolbar_state'
        ToolbarPinned      = 'force_shown'
        ToolbarUnpinned    = 'default_hidden'
    }
)

foreach (`$b in `$browsers) {
    # Managed storage - core settings
    if (!(Test-Path `$b.ManagedStorageKey)) { New-Item -Path `$b.ManagedStorageKey -Force | Out-Null }
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'showNotifications'    -PropertyType DWord  -Value $ShowNotifications    -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'enableValidPageBadge' -PropertyType DWord  -Value $EnableValidPageBadge -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'enablePageBlocking'   -PropertyType DWord  -Value $EnablePageBlocking   -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'enableCippReporting'  -PropertyType DWord  -Value $EnableCippReporting  -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'cippServerUrl'        -PropertyType String -Value '$CippServerUrl'      -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'cippTenantId'         -PropertyType String -Value '$CippTenantId'       -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'customRulesUrl'       -PropertyType String -Value '$CustomRulesUrl'     -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'updateInterval'       -PropertyType DWord  -Value $UpdateInterval       -Force | Out-Null
    New-ItemProperty -Path `$b.ManagedStorageKey -Name 'enableDebugLogging'   -PropertyType DWord  -Value $EnableDebugLogging   -Force | Out-Null

    # Managed storage - domainSquatting subkey
    `$domainSquattingKey = "`$(`$b.ManagedStorageKey)\domainSquatting"
    if (!(Test-Path `$domainSquattingKey)) { New-Item -Path `$domainSquattingKey -Force | Out-Null }
    New-ItemProperty -Path `$domainSquattingKey -Name 'enabled' -PropertyType DWord -Value $DomainSquattingEnabled -Force | Out-Null

    # Managed storage - customBranding subkey
    `$brandingKey = "`$(`$b.ManagedStorageKey)\customBranding"
    if (!(Test-Path `$brandingKey)) { New-Item -Path `$brandingKey -Force | Out-Null }
    New-ItemProperty -Path `$brandingKey -Name 'companyName'   -PropertyType String -Value '$($CompanyName -replace "'", "''")'   -Force | Out-Null

    New-ItemProperty -Path `$brandingKey -Name 'productName'   -PropertyType String -Value '$($ProductName -replace "'", "''")'   -Force | Out-Null
    New-ItemProperty -Path `$brandingKey -Name 'supportEmail'  -PropertyType String -Value '$($SupportEmail -replace "'", "''")' -Force | Out-Null
    New-ItemProperty -Path `$brandingKey -Name 'supportUrl'    -PropertyType String -Value '$($SupportUrl -replace "'", "''")'  -Force | Out-Null
    New-ItemProperty -Path `$brandingKey -Name 'privacyPolicyUrl' -PropertyType String -Value '$($PrivacyPolicyUrl -replace "'", "''")'  -Force | Out-Null
    New-ItemProperty -Path `$brandingKey -Name 'aboutUrl'      -PropertyType String -Value '$($AboutUrl -replace "'", "''")'  -Force | Out-Null
    New-ItemProperty -Path `$brandingKey -Name 'primaryColor'  -PropertyType String -Value '$PrimaryColor'  -Force | Out-Null
    New-ItemProperty -Path `$brandingKey -Name 'logoUrl'       -PropertyType String -Value '$($LogoUrl -replace "'", "''")'       -Force | Out-Null

    # Managed storage - genericWebhook subkey
    `$webhookKey = "`$(`$b.ManagedStorageKey)\genericWebhook"
    if (!(Test-Path `$webhookKey)) { New-Item -Path `$webhookKey -Force | Out-Null }
    New-ItemProperty -Path `$webhookKey -Name 'enabled' -PropertyType DWord  -Value $EnableGenericWebhook -Force | Out-Null
    New-ItemProperty -Path `$webhookKey -Name 'url'     -PropertyType String -Value '$($WebhookUrl -replace "'", "''")'     -Force | Out-Null

    # Managed storage - genericWebhook\events subkey
    `$webhookEventsKey = "`$(`$b.ManagedStorageKey)\genericWebhook\events"
    if (Test-Path `$webhookEventsKey) { Remove-Item -Path `$webhookEventsKey -Recurse -Force | Out-Null }
$(if ($WebhookEvents.Count -gt 0) {
    "    if (!(Test-Path `$webhookEventsKey)) { New-Item -Path `$webhookEventsKey -Force | Out-Null }`n"
    $i = 1
    foreach ($evt in $WebhookEvents) {
        "    New-ItemProperty -Path `$webhookEventsKey -Name '$i' -PropertyType String -Value '$($evt -replace "'", "''")' -Force | Out-Null`n"
        $i++
    }
})
    # Managed storage - urlAllowlist subkey
    `$allowlistKey = "`$(`$b.ManagedStorageKey)\urlAllowlist"
    if (Test-Path `$allowlistKey) { Remove-Item -Path `$allowlistKey -Recurse -Force | Out-Null }
$(if ($UrlAllowlist.Count -gt 0) {
    "    if (!(Test-Path `$allowlistKey)) { New-Item -Path `$allowlistKey -Force | Out-Null }`n"
    $i = 1
    foreach ($url in $UrlAllowlist) {
        "    New-ItemProperty -Path `$allowlistKey -Name '$i' -PropertyType String -Value '$($url -replace "'", "''")' -Force | Out-Null`n"
        $i++
    }
})
    # Extension settings (installation + toolbar)
    if (!(Test-Path `$b.ExtSettingsKey)) { New-Item -Path `$b.ExtSettingsKey -Force | Out-Null }
    New-ItemProperty -Path `$b.ExtSettingsKey -Name 'installation_mode' -PropertyType String -Value 'force_installed' -Force | Out-Null
    New-ItemProperty -Path `$b.ExtSettingsKey -Name 'update_url'        -PropertyType String -Value `$b.UpdateUrl     -Force | Out-Null
    if ($ForceToolbarPin -eq 1) {
        New-ItemProperty -Path `$b.ExtSettingsKey -Name `$b.ToolbarProp -PropertyType String -Value `$b.ToolbarPinned -Force | Out-Null
    } else {
        New-ItemProperty -Path `$b.ExtSettingsKey -Name `$b.ToolbarProp -PropertyType String -Value `$b.ToolbarUnpinned -Force | Out-Null
    }
}

Write-Output 'Check Chrome Extension registry keys configured successfully.'
"@

    $UninstallScript = @"
# Check Chrome Extension - Uninstall Script (generated by CIPP)
`$chromeExtensionId = '$ChromeExtensionId'
`$edgeExtensionId = '$EdgeExtensionId'

`$keysToRemove = @(
    "HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\`$chromeExtensionId",
    "HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\`$chromeExtensionId",
    "HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\`$edgeExtensionId",
    "HKLM:\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\`$edgeExtensionId"
)

foreach (`$key in `$keysToRemove) {
    if (Test-Path `$key) {
        Remove-Item -Path `$key -Recurse -Force -ErrorAction SilentlyContinue
        Write-Output "Removed: `$key"
    }
}

Write-Output 'Check Chrome Extension registry keys removed.'
"@

    $DetectionScript = @"
# Check Chrome Extension - Detection Script (generated by CIPP)
`$chromeKey = 'HKLM:\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\$ChromeExtensionId\policy'
`$edgeKey   = 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensions\$EdgeExtensionId\policy'

# Verify both managed storage keys exist
if (!(Test-Path `$chromeKey) -or !(Test-Path `$edgeKey)) { exit 1 }

# Helper to check a registry value matches expected
function Test-RegValue(`$Path, `$Name, `$Expected) {
    `$val = (Get-ItemProperty -Path `$Path -Name `$Name -ErrorAction SilentlyContinue).`$Name
    return (`$null -ne `$val -and `$val -eq `$Expected)
}

foreach (`$key in @(`$chromeKey, `$edgeKey)) {
    # Core DWORD settings
    if (!(Test-RegValue `$key 'showNotifications'    $ShowNotifications))    { exit 1 }
    if (!(Test-RegValue `$key 'enableValidPageBadge' $EnableValidPageBadge)) { exit 1 }
    if (!(Test-RegValue `$key 'enablePageBlocking'   $EnablePageBlocking))   { exit 1 }
    if (!(Test-RegValue `$key 'enableCippReporting'  $EnableCippReporting))  { exit 1 }
    if (!(Test-RegValue `$key 'updateInterval'       $UpdateInterval))       { exit 1 }
    if (!(Test-RegValue `$key 'enableDebugLogging'   $EnableDebugLogging))   { exit 1 }

    # Core string settings
    if (!(Test-RegValue `$key 'cippServerUrl'  '$CippServerUrl'))  { exit 1 }
    if (!(Test-RegValue `$key 'cippTenantId'   '$CippTenantId'))   { exit 1 }
    if (!(Test-RegValue `$key 'customRulesUrl' '$CustomRulesUrl')) { exit 1 }

    # domainSquatting subkey
    `$domainSquattingKey = "`$key\domainSquatting"
    if (!(Test-Path `$domainSquattingKey)) { exit 1 }
    if (!(Test-RegValue `$domainSquattingKey 'enabled' $DomainSquattingEnabled)) { exit 1 }

    # customBranding subkey
    `$brandingKey = "`$key\customBranding"
    if (!(Test-Path `$brandingKey)) { exit 1 }
    if (!(Test-RegValue `$brandingKey 'companyName'  '$($CompanyName -replace "'", "''")'))  { exit 1 }

    if (!(Test-RegValue `$brandingKey 'productName'  '$($ProductName -replace "'", "''")'))  { exit 1 }
    if (!(Test-RegValue `$brandingKey 'supportEmail'    '$($SupportEmail -replace "'", "''")'))    { exit 1 }
    if (!(Test-RegValue `$brandingKey 'supportUrl'       '$($SupportUrl -replace "'", "''")'))       { exit 1 }
    if (!(Test-RegValue `$brandingKey 'privacyPolicyUrl' '$($PrivacyPolicyUrl -replace "'", "''")')) { exit 1 }
    if (!(Test-RegValue `$brandingKey 'aboutUrl'         '$($AboutUrl -replace "'", "''")'))         { exit 1 }
    if (!(Test-RegValue `$brandingKey 'primaryColor' '$PrimaryColor')) { exit 1 }
    if (!(Test-RegValue `$brandingKey 'logoUrl'      '$($LogoUrl -replace "'", "''")'))      { exit 1 }

    # genericWebhook subkey
    `$webhookKey = "`$key\genericWebhook"
    if (!(Test-Path `$webhookKey)) { exit 1 }
    if (!(Test-RegValue `$webhookKey 'enabled' $EnableGenericWebhook)) { exit 1 }
    if (!(Test-RegValue `$webhookKey 'url'     '$($WebhookUrl -replace "'", "''")'))     { exit 1 }

    # genericWebhook\events subkey - verify exact count and values
    `$eventsKey = "`$key\genericWebhook\events"
$(if ($WebhookEvents.Count -gt 0) {
    "    if (!(Test-Path `$eventsKey)) { exit 1 }`n"
    $i = 1
    foreach ($evt in $WebhookEvents) {
        "    if (!(Test-RegValue `$eventsKey '$i' '$($evt -replace "'", "''")')) { exit 1 }`n"
        $i++
    }
    "    `$eventsCount = (Get-Item `$eventsKey).Property.Count`n"
    "    if (`$eventsCount -ne $($WebhookEvents.Count)) { exit 1 }`n"
} else {
    "    if (Test-Path `$eventsKey) {`n"
    "        `$eventsCount = (Get-Item `$eventsKey).Property.Count`n"
    "        if (`$eventsCount -gt 0) { exit 1 }`n"
    "    }`n"
})
    # urlAllowlist subkey - verify exact count and values
    `$allowlistKey = "`$key\urlAllowlist"
$(if ($UrlAllowlist.Count -gt 0) {
    "    if (!(Test-Path `$allowlistKey)) { exit 1 }`n"
    $i = 1
    foreach ($url in $UrlAllowlist) {
        "    if (!(Test-RegValue `$allowlistKey '$i' '$($url -replace "'", "''")')) { exit 1 }`n"
        $i++
    }
    "    `$allowlistCount = (Get-Item `$allowlistKey).Property.Count`n"
    "    if (`$allowlistCount -ne $($UrlAllowlist.Count)) { exit 1 }`n"
} else {
    "    if (Test-Path `$allowlistKey) {`n"
    "        `$allowlistCount = (Get-Item `$allowlistKey).Property.Count`n"
    "        if (`$allowlistCount -gt 0) { exit 1 }`n"
    "    }`n"
})
}

# Verify extension settings keys exist
`$chromeExtSettings = 'HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionSettings\$ChromeExtensionId'
`$edgeExtSettings   = 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\ExtensionSettings\$EdgeExtensionId'
if (!(Test-Path `$chromeExtSettings) -or !(Test-Path `$edgeExtSettings)) { exit 1 }

Write-Output 'Check Chrome Extension is correctly configured.'
exit 0
"@

    $Sha256 = [System.Security.Cryptography.SHA256]::Create()
    $SettingsHash = ([System.BitConverter]::ToString(
            $Sha256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($InstallScript))
        ) -replace '-', '').Substring(0, 16)
    $AppDescription = "Deploys and configures the Check by CyberDrain phishing protection extension for Chrome and Edge browsers. Managed by CIPP. [cfg:$SettingsHash]"

    $AssignTo = "$($Remediate.assignTo.value ?? $Remediate.assignTo ?? 'AllDevices')"
    if ("$($Remediate.customGroup)") { $AssignTo = "$($Remediate.customGroup)" }
    $ExcludeGroup = "$($Remediate.excludeGroup)"

    # Clean up the legacy OMA-URI policies from the old deployment approach.
    $LegacyPolicyNames = @('Deploy Check Chrome Extension (Chrome)', 'Deploy Check Chrome Extension (Edge)')
    $LegacyPolicies = @(New-GraphGetRequest -uri 'https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations?$select=id,displayName' -tenantid $TenantFilter | Where-Object { $_.displayName -in $LegacyPolicyNames })
    if ($LegacyPolicies.Count -gt 0) {
        $DeleteRequests = @($LegacyPolicies | ForEach-Object {
                @{ id = "delete-$($_.id)"; method = 'DELETE'; url = "deviceManagement/deviceConfigurations/$($_.id)" }
            })
        $BulkResults = New-GraphBulkRequest -tenantid $TenantFilter -Requests $DeleteRequests
        foreach ($Policy in $LegacyPolicies) {
            $Result = $BulkResults | Where-Object { $_.id -eq "delete-$($Policy.id)" }
            if ("$($Result.status)" -match '^2') {
                Write-LogMessage -API 'Baselines' -tenant $TenantFilter -message "Removed the legacy OMA-URI policy '$($Policy.displayName)'." -Sev 'Info'
            } else {
                Write-LogMessage -API 'Baselines' -tenant $TenantFilter -message "Failed to remove the legacy OMA-URI policy '$($Policy.displayName)': $($Result.body.error.message)" -Sev 'Warning'
            }
        }
    }

    # Live app read: the fingerprint gate must see the CURRENT description, not a cached one.
    $Baseuri = 'https://graph.microsoft.com/beta/deviceAppManagement/mobileApps'
    $ExistingApps = @(New-GraphGetRequest -uri "$Baseuri`?`$filter=displayName eq '$AppDisplayName'&`$select=id,displayName,description" -tenantid $TenantFilter | Where-Object { $_.'@odata.type' -eq '#microsoft.graph.win32LobApp' })

    if ($ExistingApps.Count -gt 0) {
        $ExistingHash = $null
        if ("$($ExistingApps[0].description)" -match '\[cfg:([0-9A-Fa-f]{16})\]') { $ExistingHash = $Matches[1] }
        if ($ExistingHash -eq $SettingsHash) {
            Write-LogMessage -API 'Baselines' -tenant $TenantFilter -message "$AppDisplayName settings unchanged - skipped the redeploy." -Sev 'Info'
            return
        }
        foreach ($App in $ExistingApps) {
            $null = New-GraphPostRequest -uri "$Baseuri/$($App.id)" -type DELETE -tenantid $TenantFilter
            Write-LogMessage -API 'Baselines' -tenant $TenantFilter -message "Removed the existing $AppDisplayName app to redeploy with updated settings." -Sev 'Info'
        }
        Start-Sleep -Seconds 2
    }

    $AppProperties = [PSCustomObject]@{
        displayName           = $AppDisplayName
        description           = $AppDescription
        publisher             = 'CIPP'
        installScript         = $InstallScript
        uninstallScript       = $UninstallScript
        detectionScript       = $DetectionScript
        runAsAccount          = 'system'
        deviceRestartBehavior = 'suppress'
    }
    $NewApp = Add-CIPPW32ScriptApplication -TenantFilter $TenantFilter -Properties $AppProperties
    if ($NewApp -and $AssignTo -ne 'On') {
        Start-Sleep -Milliseconds 500
        Set-CIPPAssignedApplication -ApplicationId $NewApp.Id -TenantFilter $TenantFilter -GroupName $AssignTo -ExcludeGroup $ExcludeGroup -Intent 'Required' -AppType 'Win32Lob' -APIName 'Baselines'
    }
    Write-LogMessage -API 'Baselines' -tenant $TenantFilter -message "Successfully deployed $AppDisplayName." -Sev 'Info'
}
