name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/KelvinTegelaar/CIPP-API.git  # Change this for CIPP-API
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main  # Change to master if necessary
          git merge upstream/main --no-edit
        continue-on-error: true  # Avoids breaking if merge conflicts occur

      - name: Push Changes to Fork
        run: |
          git push origin main
        continue-on-error: true  # Avoids breaking if conflicts occur
